import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Stardust from "./components/parts/StardustBG/Stardust";
import { HbgBtnContextProvider } from "./context/HbgContext";
import { SideAnimeContextProvider } from "./context/SidebarAnimation";
import { LandingAnimeContextProvider } from "./context/LandingAnimation";
import { HomeAnimeContextProvider } from "./context/HomeAnime";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Stardust/>
        <HomeAnimeContextProvider>
          <HbgBtnContextProvider>
            <LandingAnimeContextProvider>
              <SideAnimeContextProvider>
                {children}
              </SideAnimeContextProvider>
            </LandingAnimeContextProvider>
          </HbgBtnContextProvider>
        </HomeAnimeContextProvider>
      </body>
    </html>
  );
}
